version: '3'
services:
    app:
        build: .
        image: acgomes68/alpine-python:3.7.3
        container_name: python3
        restart: always
        ports:
         - "5000:80"
        volumes:
         - ./app:/app